title: Nico Gabriel R. Credito
logo: /assets/img/neikomi.jpg
description: A recent Computer Science degree holder who took courses such as basic programming, animation, databases, and game development.
#show_downloads: true
theme: jekyll-theme-minimal
